apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: assessment-frontend-config
  namespace: assessment
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
