name: Terraform Infrastructure Pipeline

on:
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'

  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: terraform-infrastructure
  cancel-in-progress: false

env:
  PROJECT_ID: gcp-gke-assessment
  TF_VERSION: 1.16.3
  TF_WORKING_DIR: terraform

jobs:
  terraform:
    name: Terraform Validate Plan Apply
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          project_id: gcp-gke-assessment
          workload_identity_provider: projects/154908148121/locations/global/workloadIdentityPools/github-actions/providers/github-provider
          service_account: github-terraform@gcp-gke-assessment.iam.gserviceaccount.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -input=false
